stages:
  - test
  - deploy

cache:
  paths:
    - .m2/repository
    - target

unit-test:
  stage: test
  image: maven:latest
  tags:
    - docker
  script:
    - echo "Maven test started"
    - "mvn test"

deploy_job:
  stage: deploy
  image: maven:latest
  when: manual
  tags:
    - docker
  script:
    - HEROKU_API_KEY=${2a1e6a5b-69b4-49e8-a93f-d3b00a753268} mvn heroku:deploy