server:
  port: ${PORT:8080}

spring:
  jdk:
    version: 17.0.7
  datasource:
    url: jdbc:postgresql://localhost:5432/ut
    username: khorkovenko
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    user:
      name: user
      password: user